# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'TBMPSkeleton' do
    pod 'GooglePlayGames', '~> 5.0'
end

target 'TBMPSkeletonTests' do
    pod 'GooglePlayGames', '~> 5.0'
end

