# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source  'sso://user/class/specs'

target 'TrivialQuest2' do
    pod 'GooglePlayGames', '~> 5.0'
    pod 'OpenSSL-Universal', '1.0.1.k'
    pod 'google-plus-ios-sdk'
end

