# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'TypeNumber' do
    pod 'GooglePlayGames', '~> 5.0'
end

target 'TypeNumberTests' do
    pod 'GooglePlayGames', '~> 5.0'
end

